services:

  web:
    container_name: app-main
    build:
      context: .
      dockerfile: Dockerfile
    # Аналог Dockerfile
    #command: /bin/bash -c "if [ ! -f /var/www/html/.env ]; then cp /var/www/html/.env.example /var/www/html/.env; fi && apache2-foreground"

    ports:
      - "5555:80"  # Пробрасываем порт 8081 хоста на порт 80 контейнера
    volumes:
      - ./public:/var/www/html/public/
      - ./bin/php:/var/www/html/bin/php/
      - ./bin/js:/var/www/html/bin/js/
    depends_on:
      - db
    networks:
      - app-network
    environment:
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  db:
    container_name: app-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_database
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  db_data:
    
networks:
  app-network:


